/**
 * Hermes Agent — Codebase Intelligence Agent (Phase 6).
 *
 * Maintains a living CODEBASE.md by:
 *   1. Computing SHA-256 hashes of all tracked files
 *   2. Comparing against .hermes/memory/file-hashes.json
 *   3. If nothing changed → exits fast (milliseconds)
 *   4. For changed files → asks LLM to summarise them
 *   5. Updates the relevant sections in CODEBASE.md
 *   6. Persists new hashes
 *
 * Usage:
 *   tsx scripts/agents/codebase-intelligence-agent.ts
 *   tsx scripts/agents/codebase-intelligence-agent.ts --force   (full re-scan)
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import * as dotenv from 'dotenv';
import fg from 'fast-glob';
import { chat } from './llm';
import { loadConfig, MEMORY_DIR, loadPrompt } from './config';
import type { FileHashStore } from './types';

dotenv.config({ path: path.join(process.cwd(), '.env') });

const HASHES_FILE = path.join(MEMORY_DIR, 'file-hashes.json');
const CODEBASE_FILE = path.join(process.cwd(), 'CODEBASE.md');
const FORCE_SCAN = process.argv.includes('--force');

// ---------------------------------------------------------------------------
// Hash utilities
// ---------------------------------------------------------------------------

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

function loadHashStore(): FileHashStore {
  if (!fs.existsSync(HASHES_FILE)) return {};
  try {
    return JSON.parse(fs.readFileSync(HASHES_FILE, 'utf8')) as FileHashStore;
  } catch {
    return {};
  }
}

function saveHashStore(store: FileHashStore): void {
  fs.mkdirSync(path.dirname(HASHES_FILE), { recursive: true });
  fs.writeFileSync(HASHES_FILE, JSON.stringify(store, null, 2), 'utf8');
}

// ---------------------------------------------------------------------------
// Codebase.md section management
// ---------------------------------------------------------------------------

function loadCodebaseMd(): string {
  if (!fs.existsSync(CODEBASE_FILE)) return buildInitialCodebaseMd();
  return fs.readFileSync(CODEBASE_FILE, 'utf8');
}

function buildInitialCodebaseMd(): string {
  return `---
lastUpdated: ${new Date().toISOString()}
trackedFiles: 0
changedOnLastScan: []
---

# CODEBASE.md — Hermes Codebase Reference

Auto-generated by the Codebase Intelligence Agent. Do not edit manually.
Changes are detected via SHA-256 file hashes. Run \`npm run hermes:codebase\` to refresh.

---

## Page Objects

<!-- HERMES:SECTION:page-objects -->
<!-- HERMES:END:page-objects -->

## Fixtures

<!-- HERMES:SECTION:fixtures -->
<!-- HERMES:END:fixtures -->

## Data Layer

<!-- HERMES:SECTION:data -->
<!-- HERMES:END:data -->

## Helpers

<!-- HERMES:SECTION:helpers -->
<!-- HERMES:END:helpers -->

## Test Patterns

<!-- HERMES:SECTION:patterns -->
Patterns are extracted from existing spec files. Run \`npm run hermes:codebase --force\` to update.
<!-- HERMES:END:patterns -->
`;
}

/** Replace or insert a named section in CODEBASE.md. */
function updateSection(
  content: string,
  sectionKey: string,
  newBody: string,
): string {
  const startTag = `<!-- HERMES:SECTION:${sectionKey} -->`;
  const endTag = `<!-- HERMES:END:${sectionKey} -->`;
  const startIdx = content.indexOf(startTag);
  const endIdx = content.indexOf(endTag);

  if (startIdx === -1 || endIdx === -1) {
    // Section doesn't exist — append it
    return content + `\n${startTag}\n${newBody}\n${endTag}\n`;
  }

  return (
    content.slice(0, startIdx + startTag.length) +
    '\n' +
    newBody +
    '\n' +
    content.slice(endIdx)
  );
}

/** Update the frontmatter header in CODEBASE.md. */
function updateFrontmatter(
  content: string,
  trackedFiles: number,
  changedFiles: string[],
): string {
  const newFrontmatter = `---
lastUpdated: ${new Date().toISOString()}
trackedFiles: ${trackedFiles}
changedOnLastScan: [${changedFiles.map((f) => `'${f}'`).join(', ')}]
---`;

  // Replace existing frontmatter
  return content.replace(/^---[\s\S]*?---/, newFrontmatter);
}

// ---------------------------------------------------------------------------
// File classification
// ---------------------------------------------------------------------------

function classifyFile(
  filePath: string,
): 'page-objects' | 'fixtures' | 'data' | 'helpers' | null {
  if (filePath.startsWith('pages/')) return 'page-objects';
  if (filePath.startsWith('fixtures/')) return 'fixtures';
  if (filePath.startsWith('data/')) return 'data';
  if (filePath.startsWith('helpers/')) return 'helpers';
  return null;
}

// ---------------------------------------------------------------------------
// LLM scan
// ---------------------------------------------------------------------------

async function scanFileWithLLM(
  relPath: string,
  content: string,
): Promise<string> {
  const promptTemplate = loadPrompt('codebase-scan', {
    FILE_PATH: relPath,
    FILE_CONTENT: content,
  });

  const response = await chat([
    {
      role: 'system',
      content:
        'You are a code documentation expert. Follow the output format instructions exactly. ' +
        'Output ONLY the Markdown section content — no preamble, no code fence around the output.',
    },
    { role: 'user', content: promptTemplate },
  ]);

  return response.trim();
}

// ---------------------------------------------------------------------------
// Main agent
// ---------------------------------------------------------------------------

export async function run(): Promise<void> {
  const config = loadConfig();
  const trackedGlobs = config.codebaseAgent.trackedGlobs;

  // 1. Resolve all tracked files
  const files = await fg(trackedGlobs, {
    cwd: process.cwd(),
    onlyFiles: true,
    ignore: ['node_modules/**'],
  });
  files.sort();

  console.log(
    `[codebase] Tracking ${files.length} files across ${trackedGlobs.length} globs`,
  );

  // 2. Compute current hashes
  const currentHashes: FileHashStore = {};
  for (const relPath of files) {
    const absPath = path.join(process.cwd(), relPath);
    const content = fs.readFileSync(absPath, 'utf8');
    currentHashes[relPath] = {
      sha256: sha256(content),
      lastScannedAt: new Date().toISOString(),
    };
  }

  // 3. Compare against stored hashes
  const storedHashes = FORCE_SCAN ? {} : loadHashStore();
  const changedFiles = files.filter(
    (f) =>
      !storedHashes[f] || storedHashes[f].sha256 !== currentHashes[f].sha256,
  );

  if (changedFiles.length === 0) {
    console.log(
      '[codebase] No changes detected — CODEBASE.md is up to date. Exiting.',
    );
    return;
  }

  console.log(
    `[codebase] ${changedFiles.length} file(s) changed: ${changedFiles.join(', ')}`,
  );

  // 4. Scan changed files and update CODEBASE.md
  let codebaseMd = loadCodebaseMd();
  const sectionUpdates: Record<string, string[]> = {
    'page-objects': [],
    fixtures: [],
    data: [],
    helpers: [],
  };

  // Collect existing sections to merge with
  for (const section of Object.keys(sectionUpdates)) {
    const startTag = `<!-- HERMES:SECTION:${section} -->`;
    const endTag = `<!-- HERMES:END:${section} -->`;
    const startIdx = codebaseMd.indexOf(startTag);
    const endIdx = codebaseMd.indexOf(endTag);
    if (startIdx !== -1 && endIdx !== -1) {
      const existing = codebaseMd
        .slice(startIdx + startTag.length, endIdx)
        .trim();
      if (existing) sectionUpdates[section].push(existing);
    }
  }

  for (const relPath of changedFiles) {
    const section = classifyFile(relPath);
    if (!section) continue;

    console.log(`[codebase] Scanning ${relPath}...`);
    const absPath = path.join(process.cwd(), relPath);
    const content = fs.readFileSync(absPath, 'utf8');

    try {
      const summary = await scanFileWithLLM(relPath, content);
      // Replace the existing entry for this file (if present) or append
      const fileMarker = `\`${relPath}\``;
      const existingIdx = sectionUpdates[section].findIndex((s) =>
        s.includes(fileMarker),
      );
      if (existingIdx !== -1) {
        sectionUpdates[section][existingIdx] = summary;
      } else {
        sectionUpdates[section].push(summary);
      }
    } catch (err) {
      console.warn(
        `[codebase] LLM scan failed for ${relPath}: ${(err as Error).message}`,
      );
    }
  }

  // 5. Write updated sections back to CODEBASE.md
  for (const [section, entries] of Object.entries(sectionUpdates)) {
    if (entries.length > 0) {
      codebaseMd = updateSection(
        codebaseMd,
        section,
        entries.join('\n\n---\n\n'),
      );
    }
  }
  codebaseMd = updateFrontmatter(codebaseMd, files.length, changedFiles);

  fs.writeFileSync(CODEBASE_FILE, codebaseMd, 'utf8');
  console.log(
    `[codebase] ✓ CODEBASE.md updated with ${changedFiles.length} change(s)`,
  );

  // 6. Persist updated hashes
  const updatedStore: FileHashStore = { ...storedHashes };
  for (const [file, entry] of Object.entries(currentHashes)) {
    updatedStore[file] = entry;
  }
  saveHashStore(updatedStore);
  console.log(`[codebase] Hash store updated for ${files.length} file(s)`);
}

// ---------------------------------------------------------------------------
// CLI entry
// ---------------------------------------------------------------------------

if (require.main === module) {
  run()
    .then(() => {
      console.log('[codebase] Done.');
    })
    .catch((err: Error) => {
      console.error(`[codebase] Fatal: ${err.message}`);
      process.exit(1);
    });
}
